### PR TITLE
waltz-has-role-for-entity-kind directive and apply to person/entity a…

### PR DESCRIPTION
**Pull request by kamransaleem**
…ssociation edit button

#2167

### CODE REVIEW

**Comment by davidwatkins73** [comment]
did this have to be a directive ?

**Comment by kamransaleem** [comment]
as a component, you have to 'restrict' to elements.  The usage would be different from `has-role` so I figured I would keep it as a directive for consistency.  

thoughts?

**Comment by davidwatkins73** [comment]
how would the usage be different ?

**Comment by kamransaleem** [comment]
So present it's restricted to an attribute as follows:

`<some-element waltz-has-role="userRole"> content </some-element>`

as a component, the only support usage is as an element selector, so you have as follows:

`<waltz-has-role role="userRole">
  <some-element> content </some-element>
</waltz-has-role>`

unless I'm mistaken.

In this case, it would be a bit verbose.  Plus the directive version has `replace` as true which ensure no funny business with our current styles. 

I can spike moving to a component to assess the impact?

**Comment by davidwatkins73** [comment]
Create an issue and we'll spike at beginning of 1.5 cycle.

**Comment by kamransaleem** [comment]
#2180

**Pull request merged**
