### PR TITLE
Make contact email nullable on survey run

### PR DESCRIPTION
**Pull request by rovats**
#1422

### CODE REVIEW

**Comment by davidwatkins73** [comment]
why?  Surely a contact email is a good thing to have.... ?

**Comment by rovats** [comment]
But should it be mandatory? For eg: you could say in the description, if you have any questions contact someone with a certain role from your department, and not have a single email address?

**Comment by davidwatkins73** [comment]
Would have thought if differing areas have responsibility then it should be broken into an appropriate set of `runs` so that it can be tracked against them.

**Comment by davidwatkins73** [comment]
Gut feel is that we should keep it mandatory.

**Comment by rovats** [comment]
OK, let's keep it mandatory. 

But if the surveys are different runs, it might be difficult to aggregate overall results. Although that doesn't mean there can't be a single point of contact.

**Comment by davidwatkins73** [comment]
good point re-aggregation.  We'll have to think about that......

**Comment by rovats** [comment]
OK, should I close this pull request?

**Comment by davidwatkins73** [comment]
yep - we can redo if needed.

**Pull request closed without merging**
