### PR TITLE
NWM-Contrib: Nav aids: allow SVG export (download)

### PR DESCRIPTION
**Pull request by NWM-OS**
#4568

### CODE REVIEW

**Comment by davidwatkins73** [comment]
Would using the external-id resolver route make things simpler ?

The resolver lives in [entity/routes.js](https://github.com/khartec/waltz/blob/master/waltz-ng/client/entity/routes.js#L61) and given an entity kind and an external id will attempt to open the right page (if multiple are found it prompts the user to choose from a list of matches).

This might cut the need for a lot of the resolver code in this PR.....

The main -ve would be the lack of support for measurable-category - though perhps this could be added as an additional option to the route.

**Comment by rovats** [comment]
Have made the following changes (pending internal review):

* Use `/entity` routes in the java code:
```
public class EntityLinkUtilities {

    public static String mkIdLink(String baseUrl, EntityKind kind, Long id) {
        return baseUrl + "entity/" + kind.name() + "/id/" + id;
    }


    public static String mkExternalIdLink(String baseUrl, EntityKind kind, String externalId) {
        return baseUrl + "entity/" + kind.name() + "/external-id/" + externalId;
    }
}
```

* Use `mkExternalIdLink` for `DATA_TYPE` and `PERSON`, and `mkIdLink` for `ORG_UNIT`.
These just use the values embedded in the SVG, removed the resolver logic in `NavAidExtractor` for these.

* For `MEASURABLE`, still resolve the external id in java, but now use `mkIdLink`.

Does this sound OK?

**Comment by davidwatkins73** [comment]
That sounds like a good set of changes.  Should cut down on the amount of coded needed and exercises the existing features.

**Comment by rovats** [comment]
@davidwatkins73 pull request updated, please review.

**Pull request merged**
